rg_name                = "rg-personal-bot"
ai_search_name         = "ai-search"
openai_name            = "openai"
sa_name                = "storage"
container_name         = "content"
location               = "eastus"
deployment_name        = "chatgpt4o"
