rg_name                = "RG-openAI-demo"
ai_search_name         = "ai-search-rxt-demo"
openai_name            = "openai-rxt-demo"
sa_name                = "openaisademo01"
container_name         = "democontainer"
location               = "eastus"
deployment_name        = "chatgpt4o"
